version: '3.1'

services:

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
       - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
       TOKEN_KEY : "8K1CSM11SUd3DXEk8CK/Xx9WBX5ENTiqns2UIDlOhoLZ0EgabFPEhGTKBPmBGQI6gtzoXjIqA2MsYFd+SMkwF8VQ0gevMsJGXZtNwNMLVQ8abSjWUsa4NTAZre9BVudErTE1wHxINK+uL1Nov1xuGxroxFEEUuPvEbITtJfqdnytuacVe9Dbn0o0BAq3OrPISAjbpNmkCkdps2E3p1dWGXtktsAlLHvOpqoKZxoPzbJnB1Z7lGr7YwC3exQg7u+ZB5NFuw6NyMxi78xto0cGjMfPJ6LIkj3Phfx3UrqvyYYiSxlzGpxRBgMCnWWNsLJYbCh7SOjh8ynCtFNUU0w7sA=="
       MONGO_HOST : "host.docker.internal"
       MONGO_PORT : 27017
       MONGO_DB : "testnode"
       MONGO_USER : "root"
       MONGO_PASSWORD : "example"
    image: apintestalten
    container_name: apintestalten
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
    - 81:8083